### ISSUE TITLE
Ch3_book.ipynb Listing 3.3

### ISSUE THREAD

**Issue by haohaoxiao** [DeepReinforcementLearning/DeepReinforcementLearningInAction#14]
**state1** = torch.from_numpy(state_).float() #E

**Comment by outlace** [comment]
Thanks! We are fixing the errors and have fixed versions in the Errata folder, e.g. https://github.com/DeepReinforcementLearning/DeepReinforcementLearningInAction/blob/master/Errata/Chapter%203.ipynb

We will update the main notebooks soon.
