### ISSUE TITLE
Ch3_book.ipynb Listing 3.3: Different sizes for the loss_fn

### ISSUE THREAD

**Issue by Carsten-R** [DeepReinforcementLearning/DeepReinforcementLearningInAction#15]
How to resolve this warning:
> UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
caused by this code part:
```
        Y = torch.Tensor([Y]).detach()
        X = qval.squeeze()[action_]
        loss = loss_fn(X, Y)
```
The script still works fine, but I would like to get rid of the warning. Thanks

**Comment by outlace** [comment]
Try Y.squeeze() in `loss_fn(X, Y.squeeze())`
