### ISSUE TITLE
Chapt 8: Curiosity Driven Deep Learning RAM Requirements 

### ISSUE THREAD

**Issue by JulesVerny** [DeepReinforcementLearning/DeepReinforcementLearningInAction#18]
I have attempted to Chapt 8 code, as a python file,  on a 32Gb CPU RAM Ubuntu 18.04 rig with 16Gb NVidia 1800 GTi GPU card.  However my RAM Utilisation grows excessively as the training epochs run, exceeds 30 Gb when I hit 1800 epochs on the Super Mario Mario Curiosity Deep Training code. 

The book suggested that this code would only take 30 minutes on a Mac Book Air (no GPU) So i don’t understand why the RAM use grows to excess as the training epochs grows. 

Interested in any others experience on this, or why I would be experiencing such excessive and growing RAM utilisation.

**Comment by outlace** [comment]
After training for about 30 minutes on a MacBook Air you could get an agent that was at least able to progress through the most of the first level - just demonstrating that the algorithm is working. It won’t be able to do much more than that with such short training. I’ll review the code when I get a chance, it must be storing something that doesn’t need to be stored each loop iteration.

**Comment by JulesVerny** [comment]
OK, I have attempted to run this in Windows 10 (I didn't think the Atari games would run in Windows  from previous AI Gym experience. )

I encountered no problems, the code runs well, and trains the networks, and trains a pretty useful Mario Agent Player. 

So it must be something odd , with my own Ubuntu python environment.
