### ISSUE TITLE
some pictures go blank in eBook!

### ISSUE THREAD

**Issue by DemonsHunter** [DeepReinforcementLearning/DeepReinforcementLearningInAction#23]
I am very happy and grateful to read this brilliant book！
 
But I recently find some pictures in book is blank. In my case, Figure 3.17, 3.18, 4.5 are all blank. 

I read the eBook from O'reilly, and I do hope these pictures can show up so that readers can understand all authors' thoughts!

**Comment by outlace** [comment]
Thanks for the kind words! The book is originally published by Manning, I did not know O'reilly was re-selling. We will have to reach out to the publisher to inquire about the missing graphics. Thanks for letting us know
