### ISSUE TITLE
Ch 3 - Without experience replay: invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by FatherShawn** [DeepReinforcementLearning/DeepReinforcementLearningInAction#6]
Running the cell in notebook produces the following error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-448853d32d49> in <module>
     34         optimizer.zero_grad()
     35         loss.backward()
---> 36         losses.append(loss.data[0])
     37         optimizer.step()
     38         state = new_state

IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
```

Python 3.7.2 with:
[('Jinja2', '2.10.1'), ('Mako', '1.0.7'), ('Markdown', '3.0.1'), ('MarkupSafe', '1.1.0'), ('Pillow', '6.0.0'), ('Pygments', '2.3.1'), ('Send2Trash', '1.5.0'), ('appnope', '0.1.0'), ('attrs', '19.1.0'), ('backcall', '0.1.0'), ('bleach', '3.1.0'), ('cycler', '0.10.0'), ('decorator', '4.4.0'), ('defusedxml', '0.6.0'), ('entrypoints', '0.3'), ('ipykernel', '5.1.0'), ('ipython', '7.4.0'), ('ipython-genutils', '0.2.0'), ('ipywidgets', '7.4.2'), ('jedi', '0.13.3'), ('jsonschema', '3.0.1'), ('jupyter', '1.0.0'), ('jupyter-client', '5.2.4'), ('jupyter-console', '6.0.0'), ('jupyter-core', '4.4.0'), ('kiwisolver', '1.0.1'), ('matplotlib', '3.0.3'), ('mistune', '0.8.4'), ('nbconvert', '5.4.1'), ('nbformat', '4.4.0'), ('notebook', '5.7.8'), ('numpy', '1.16.3'), ('pandocfilters', '1.4.2'), ('parso', '0.4.0'), ('pdoc3', '0.5.2'), ('pexpect', '4.7.0'), ('pickleshare', '0.7.5'), ('pip', '19.0.3'), ('prometheus-client', '0.6.0'), ('prompt-toolkit', '2.0.9'), ('ptyprocess', '0.6.0'), ('pyparsing', '2.4.0'), ('pyrsistent', '0.14.11'), ('python-dateutil', '2.8.0'), ('pyzmq', '18.0.1'), ('qtconsole', '4.4.3'), ('setuptools', '40.8.0'), ('six', '1.12.0'), ('snap', '5.0.0-64-dev-macosx10.14.3-x64-py3.7'), ('terminado', '0.8.2'), ('testpath', '0.4.2'), ('torch', '1.0.1.post2'), ('torchvision', '0.2.2.post3'), ('tornado', '6.0.2'), ('traitlets', '4.3.2'), ('wcwidth', '0.1.7'), ('webencodings', '0.5.1'), ('wheel', '0.33.0'), ('widgetsnbextension', '3.4.2')]

**Comment by outlace** [comment]
Thanks for reporting the issue. We'll have a look and update soon.

In the meantime, try just changing that line to `losses.append(loss.data.detach().numpy())` or just `losses.append(loss.data)`

**Comment by FatherShawn** [comment]
`losses.append(loss.data)` ran without issue:
![image](https://user-images.githubusercontent.com/414635/56603519-df443100-65cd-11e9-9b47-c162552590e5.png)

I'm not sure `losses.append(loss.data.detach().numpy())` is producing valid output.  The plot doesn't smell right:
![image](https://user-images.githubusercontent.com/414635/56603688-30542500-65ce-11e9-84bf-34b77d0bb78c.png)

**Comment by outlace** [comment]
Can you post what you get for `loss.data.shape`

**Comment by FatherShawn** [comment]
`print (loss.data.shape)` => torch.Size([])

via the notebook.  I can copy the code into pyCharm and set a breakpoint if you want more detail.

**Comment by outlace** [comment]
it has to be in your training loop after you call `loss.backward()`
just set your max epochs to 10 or something so it doesn't keep printing thousands of times

**Comment by FatherShawn** [comment]
So if I bring this code into pyCharm and add a line like so:
```
loss.backward()
check_shape = loss.data.shape
```
and break after the assignment, `check_shape` is of class `Size`
<img width="442" alt="check_shape" src="https://user-images.githubusercontent.com/414635/56606850-1f5ae200-65d5-11e9-87f5-36c101ac78a8.png">

**Comment by outlace** [comment]
It shouldn't be size 0.. you were able to get values to plot above

**Comment by FatherShawn** [comment]
Here's the full tensor from the debugger:
![loss_object](https://user-images.githubusercontent.com/414635/56607993-cfc9e580-65d7-11e9-95ac-013ef672e0ec.png)

**Comment by outlace** [comment]
We've uploaded new code Chx_book.ipynb notebooks that should all work for all chapters
